### ISSUE TITLE
A user should receive daily digest about today's activity

### ISSUE THREAD

**Issue by vlasiak** [vlasiak/rails_tada#15]
Registered users should receive daily digest so that shows about today's activity (completed items and a new lists).

**Comment by sergeyradkevich** [comment]
Colors:
- Header and footer: `#1e8cd4`
- Completed amount: `#34ad00`
- Remaining amount: `#1f8cd3`

The mock-up:
![digest](https://cloud.githubusercontent.com/assets/2563629/8871308/0ebd02d0-31fd-11e5-80a6-c9b9eaecfb29.jpg)

**Comment by vlasiak** [comment]
@sergeyradkevich, I suppose this user story is too big for one iteration and needs to be exploded some way. For example, I suggest to create 2 user stories:
1. 'A user should be informed about his activity' (immediately sending an email on some action and saving it in a db for the statistic).
2. 'A user can receive daily digest' (sum up user's daily activity and send it in an email at the midnight. Besides cancel immediately email sending will be done here).

What do you think about this?

**Comment by sergeyradkevich** [comment]
Hey @vlasiak, thanks for the notice. I do not think there is a sense to spend time on (and then revert that functionality later)

> immediately sending an email on some action and saving it in a db for the statistic

because it would not bring any value into the project.

Can you please elaborate what is the most complex thing here? May be based on that we could make better splitting into smaller ones?

**Comment by vlasiak** [comment]
@sergeyradkevich, the most difficult thing here for me is to make a daily email sending, as I would have to create a job for statistic gathering and sending it via email at the specific time every day.
So the first part of the task is to track and save user's activity and the second - to notify user. 
But in this case I don't really see any project value in the first user story.

**Comment by sergeyradkevich** [comment]
I see. @vlasiak, let's have a meeting on this today.

**Comment by vlasiak** [comment]
Exploded on separate user stories: #16, #17, #18, #19.

**Comment by vlasiak** [comment]
@sergeyradkevich, I've closed this issue. You can view for the details in the message above.
